### ISSUE TITLE
Feature Request - Dissenter On Sidebar

### ISSUE THREAD

**Issue by TheChiefMeat** [gab-ai-inc/gab-dissenter-extension#16]
Would be great if we could have Dissenter open in the Firefox Sidebar using sidebar_action so comments can always be seen, regardless of what page you're on.

**Comment by eveneveneven** [comment]
It would definitely make the app more appealing and create more engagement.
At the moment you have to (if you remember, maybe you are just browsing after all) press the button and scroll through comments in a claustrophobic tight space every time you want to engage.

What if you could inject some fixed or even floating customizable bar, docking top/bottom/right/left or whatever.
With a collapse button to easily show hide when you need more space for your browsed page.
While we add custom settings, might as well allow individual settings for pages/domains to keep the bar from being a nuisance where it's not wanted. I'm thinking personal settings, but even some defaults for different popular websites sounds like could be a great idea to better integrate it into the websites.

This goes a little beyond the Firefox Sidebar (I'm using Chrome) but injecting to the DOM would work for all browsers I guess.
Just a couple of thoughts off the top of my head.

**Comment by maietta** [comment]
A colleague and myself have worked out a very similar idea of a project called Abuty! that aims to solve exactly the same problem Dissenter solves, but with a number of differences to help ensure privacy on the platform. With that in mind...

R&D shows the benefits with JS and CSS being injected into the page itself is that the SSL icon doesn't have to "break" and the page functions perfectly as normal. It's no different than loading say, a Twitter widget.  I've been successful in injecting JS and CSS into DOM to draw a slide-out type UI that loads a comments section from a separate and unrelated domain to the page i'm visiting. So i know this technique will work flawlessly.

Perhaps I can contribute the necessary changes at some point, to change the way the tab loads comments. Instead of an overlay, injecting the JS and CSS necessary to load up the comments section as normal but in the page itself. I don't know if this would be an accepted feature, but it sure would be nice.

**Comment by TheChiefMeat** [comment]
This feature is now included in the release build, thank you to both the developers of Dissenter and thank you to @mastnejsalam for making this happen :)

**Comment by danuker** [comment]
@TheChiefMeat : I am not sure you closed the right ticket. I do not see a sidebar with the newest Firefox release.

**Comment by TheChiefMeat** [comment]
This was the only ticket I had open, and I have the feature now in the Firefox sidebar.
