### ISSUE TITLE
Dissenter Buttons/Extension doesn't display unless you manually browse to dissenter first to allow CloudFlare detection

### ISSUE THREAD

**Issue by optoisolated** [gab-ai-inc/gab-dissenter-extension#42]
Dissenter Buttons/Extension doesn't display unless you manually browse to dissenter first to allow CloudFlare detection. Once the cloudflare detection is completed, the browser extension and popup windows work as intended. 

Noticed on FireFox 65.0.2.

**Comment by mgabdev** [comment]
Hi @optoisolated thanks for submitting this issue. This occurred when we experiencing a DDoS attack so we flipped on "attack mode" in CloudFlare which limited the extension's functionality during that short time period. 

I will be closing this out as it's not major now that we have more safeguards in place to protect against these attacks. However, it _is_ expected behavior that while in "attack mode", one would have to go to dissenter.com, let CloudFlare’s detection run, then re-open the extension.
