### ISSUE TITLE
[Firefox] YouTube videos don't get comment pages connected correctly when video contains URL data after v=xxxxxxxx

### ISSUE THREAD

**Issue by optoisolated** [gab-ai-inc/gab-dissenter-extension#43]
YouTube videos don't get comment pages connected correctly when video contains URL data after the video Identifier.

Example URL: https://www.youtube.com/watch?v=xxxxxxxxxxx&feature=push-prem-sub&attr_tag=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Noted when viewing a Premiere video.

**Comment by mgabdev** [comment]
Hi @optoisolated thank you for submitting an issue. This is expected behavior. (Nearly all) Query parameters on urls designate a brand new url. For example, on youtube all video urls contain a `?v=xxxxxxxxx`. Any additional parameters (such as `feature=...` or `tag=...`) create an entirely new comment page on dissenter.

The reason for this is that it would be difficult to differentiate or associate a page by ignoring _some_ query parameters while others are key to that url. 

When I said "nearly all" above, we _do_ actually ignore/remove certain query parameters such as the `utm` tags.

A solution to this issue would be to remove the additional query parameters `feature=...` and `attr=...` in order to have the standard url structure that youtube videos resolve to: ` https://www.youtube.com/watch?v=xxxxxxxxxxx`
