### ISSUE TITLE
Images & JavaScript don't load in extension-controlled browser views on Brave

### ISSUE THREAD

**Issue by kakolisgay** [gab-ai-inc/gab-dissenter-extension#44]
The Dissenter iFrame [isn't loading Javascript or Images](https://i.imgur.com/k6g3Vmp.png) on Brave.

Dissenter works fine if I open the exact same url in an actual tab. I've tried disabling uMatrix and manually whitelisting dissenter in Site Settings and still nothing. 

Using the network inspector shows that the iFrame isn't requesting images or javascript, however even when dissenter is manually whitelisted in Site Settings it doesn't seem to effect the iFrame. https://i.imgur.com/bIe8VHC.png 

Since fonts are being blocked I'd have to assume Brave's shields are doing something. 

This issue only effects pages/views controlled by the extension, opening the exact same URL in a normal windows works just fine, even with Brave Shields on. https://i.imgur.com/g6x0Tyk.png 

I'd assume this probably is a side-effect of Brave's aggressive Shields, or Site Settings effecting extension-controlled popups/views differently.

[Gab Thread](https://gab.com/kakol/posts/a0tyTzFDS05hVUZJamMveS9YcHpvZz09)

**Comment by mgabdev** [comment]
Hi @kakolisgay thanks for submitting an issue. I am not experiencing this problem when I give a test on Brave just now. However, that may be due to us having different settings or activated shields...
Given that, would you mind listing here (or screenshotting if you prefer) what type of settings you have within Brave as well as the version number.

Also, the "Gab Thread" link you have heads to a 404.

Looking forward to hearing back and seeing how I can help.

**Comment by kakolisgay** [comment]
@mgabdev I think gab changed the post id for the thread, fixed it now.

Brave: 0.60.47 Chromium: 72.0.3626.119
Brave Shields:
![image](https://user-images.githubusercontent.com/16590431/54824624-633f8c00-4ca3-11e9-9a2e-625c8582df16.png)
Site Settings (Dissenter is whitelisted for both):
![image](https://user-images.githubusercontent.com/16590431/54824871-17411700-4ca4-11e9-9cff-3f9beedc1d79.png)

Site settings aren't exclusive to brave, they're a chromium feature so you may want to test these settings on chromium first.

**Comment by mgabdev** [comment]
Hi @kakolisgay, I have discovered a solution. In order to get javascript and images working from within the extension, it is not only necessary to include dissenter.com as a whitelisted website (in order to get the main website working) but to also add the extension's unique url to the whitelist for javascript and image blocking.

In order to find the extension's unique url, you can navigate to the extensions page (e.g. `brave://extensions`), find the Dissenter Extension, click the "**Details**" button, scroll down and find "**ID**".
For example, on my computer the ID is showing up as: `hfmlagllaeboigmfkcdlbfooibmknapj`. (It very well may be different on your computer).

Once you have that ID, you will then need to navigate to the settings page to edit the javascript and images URL whitelist.
Input the whitelisted url with the following pattern:
`chrome-extension://[ID]`
For example, in my case, it would be: `chrome-extension://hfmlagllaeboigmfkcdlbfooibmknapj`

Once I have added that extension URL to the whitelist for both javascript and images, the extension works as intended.

Please let me know if this solution works for you.

**Comment by kakolisgay** [comment]
@mgabdev Yeah works for me, you might be able to automate this by using Chrome's site permission api or just by writing a help article and pointing users to it if they have javascript disabled and are requesting the extension-specific page.

**Comment by kakolisgay** [comment]
Also, clicking on external links results in this.
![image](https://user-images.githubusercontent.com/16590431/56409928-1388bc00-6273-11e9-9427-92d8546ab315.png)

**Comment by mgabdev** [comment]
@kakolisgay With the latest release of r9 (https://github.com/gab-ai-inc/gab-dissenter-extension/releases/tag/r9), a .crx file has been circulated. For all other issues, please submit a new issue. Thanks!
