### ISSUE TITLE
Browser Extension not working on Microsoft Edge

### ISSUE THREAD

**Issue by aidangwolf** [gab-ai-inc/gab-dissenter-extension#48]
When clicking on the icon in the bar at the top, it just comes up with a loading icon on a white background...

**Comment by mgabdev** [comment]
Hi @aidangwolf thanks for submitting this issue. Can you let me know if there are any errors you are seeing with the extension in the developer console or in the extension settings? Will do additional testing on our side in the mean time.

**Comment by Dylan-P-Green** [comment]
I have the same issue. Edge has the following errors for me:

Unrecognized manifest key '-ms-preload'.
Unrecognized manifest key 'Key'.

**Comment by SeriousBurnsUnit** [comment]
Similar problem as the OP
console message:  CONSOLE21301: serviceWorker.getRegistrations is rejected due to unsecure context or host restriction in ms-browser-extension://DissenterExtension_840582F94AC640A7BA1FB5FBA98D2EAD/popup/popup.html.

all I see us this
![Capture](https://user-images.githubusercontent.com/49060862/55223069-5a712c00-5248-11e9-879d-ae35904cff4c.PNG)

**Comment by thegnskar** [comment]
Same issue. When I enter Dissenter through a "Dissent This" link, like in YouTube, it works fine, but the button next to the search bar just brings up a loading screen.

**Comment by mgabdev** [comment]
Hi all, in the latest release of r9, the Dissenter Microsoft Edge extension is now working. https://github.com/gab-ai-inc/gab-dissenter-extension/releases/tag/r9
