### ISSUE TITLE
Login/registration does not work properly in Firefox with various security/privacy features enabled

### ISSUE THREAD

**Issue by propolisor** [gab-ai-inc/gab-dissenter-extension#52]
When you click the login/register button in the extension's interface, it opens a tab in your browser to the Dissenter site, which allows you to do just that. However, if you have various security/privacy features in Firefox enabled (I have too many to disable them all to check, but I bet first party cookie isolation causes it), the cookies set in the website's tab do not carry over to the context of the extension's interface (the box that pops up when you click it). In order to ameliorate this issue and allow for proper posting, the login/registration form should exist/be loaded within the interface itself.

**Comment by PongoPygmaeus** [comment]
Can confirm that disabling first-party cookie isolation unbreaks the extension

**Comment by mgabdev** [comment]
Hi @propolisor @PongoPygmaeus, the extension as it stands today relies on cookies to detect if you are logged in to dissenter.com. If by disabling the "first-party cookie isolation" as stated is a viable solution, or if there's a whitelist option for enabling dissenter.com cookies that may be a good bet. 
Otherwise, it would be difficult to troubleshoot all of the possible issues if you have multiple security/privacy features that are enabled in Firefox.

Closing this out as it's too specialized and we have a solution above.

**Comment by propolisor** [comment]
@mgabdev

Disabling "first party isolation" is not a solution. It is an incredibly important privacy feature, as someone who works at a social media company that's an alternative to companies like Facebook (which uses people not having first party isolation enabled to track them across the web) should know.

The solution is for you to put the login context in the same context as all of the other web content the extension displays, which should take about five minutes to implement.

In fact, if you click the "Sign Up" button in the extension, it *already* behaves like this (though you seem to have somehow broken it server-side somehow recently, at least for me). You literally only have to take the same behavior and apply it to the "Log In" button.

There is zero reason why this should be a wontfix issue.
