### ISSUE TITLE
Count showing on Dissenter icon on browser bar does not account for Deleted posts  

### ISSUE THREAD

**Issue by sgornick** [gab-ai-inc/gab-dissenter-extension#57]
Dissenter v0.1.5, on Chromium v73.

Just love how Dissenter now (as of v0.1.5) will display in red the count of posts for that URL.  What I found though is that if I was the author of that post, and delete it, the counter showing will still show a number that includes that deleted post. 

I used Dissenter to create a second post and then delete it, and that counter now shows 2, even after refreshing the page, and then even clearing browser data and restarting.

When I click on the dissenter icon in the browser bar, with the red "2" showing, I see it then shows:
"There are no comments at this time."

So appears whatever is keeping count of posts needs to be made aware of deletions of posts.

**Comment by mgabdev** [comment]
Hi @sgornick thank you for submitting this issue. Glad you like the comment count badge.

As for the issue, upon deliberation with the team, this feature is actually working as expected.

The idea behind it is that if someone were to post a comment on a URL via Dissenter, that comment is treated as a node in the system. If that comment were to be deleted by its author, its node would still exist. It would delete the comment and show a message of "This comment has been deleted by its author". This is done in order to maintain sub-comments that have been made under that parent comment. If there are replies to that main comment, deleting the main comment would result in a broken chain. 

In total, yes, if a comment is made and then deleted the count would still maintain it's count of +1 instead of +/- 0.

Hope this makes sense for you and those wondering.
Feel free to post more feedback if you have it under this issue.

However, for the time being, closing this out.
